### PR TITLE
Translate consolidated extension

### LINKED ISSUE #159: Translating the consolidated extension
Currently the patched PPP schema and compiled codelists for the PPP profile are translated as part of the docs build.

Prior to the changes in #142 publishers declared the PPP profile by declaring the individual extensions which comprise it and because extensions aren't translated at source these were the EN versions of the extensions.

Following the changes in #142 publishers now declare the PPP profile by declaring the consolidated extension and because the consolidated extension is built from the untranslated extensions (using `apply-extensions.py`) this is also untranslated.

For anyone developing a tool to publish OCDS for PPPs data, they can use the full schema (which is translated), for example to display field descriptions in an interface, but for 'extension aware' tooling which consumes OCDS data, e.g. to display translated field descriptions in CoVE, we would need to have a translated version of the consolidated extension for users to declare.

This is related to https://github.com/open-contracting/standard/issues/704.

### PR DESCRIPTION
**Pull request by jpmckinney**
Closes #159 

Just need to test that it works once built (works locally).

### CODE REVIEW

**Comment by jpmckinney** [comment]
These work:

* http://standard.open-contracting.org/profiles/ppp/translated-consolidated-extension/es/extension.json
* http://standard.open-contracting.org/profiles/ppp/translated-consolidated-extension/es/release-schema.json

This doesn't work, though it's translated and built locally under e.g. `build/es/codelists`:

* http://standard.open-contracting.org/profiles/ppp/translated-consolidated-extension/es/codelists/dataType.json

I'm probably forgetting something about the deployment.

**Comment by jpmckinney** [comment]
Ha! Nevermind, I just made a copy-paste error and forgot to change the extension from `json` to `csv`.

The codelists are also translated: http://standard.open-contracting.org/profiles/ppp/translated-consolidated-extension/es/codelists/dataType.csv

My browser shows strange characters, I assume because it's not guessing the encoding correctly, and the HTTP headers don't specify one. When I `curl` I get correct characters.

**Comment by jpmckinney** [comment]
@duncandewhurst Would you like to test if http://standard.open-contracting.org/profiles/ppp/translated-consolidated-extension/es/extension.json works as an extension URL with CoVE? If so, I think we can merge this.

**Comment by duncandewhurst** [comment]
The URL works, but CoVE fails to patch the codelists because the headings in the translated version have been translated too (e.g. code is now 'codigo')

image

(I also noticed the typo which I've [fixed](https://github.com/OpenDataServices/cove/pull/1041))

**Comment by jpmckinney** [comment]
Hmm, well our approach to translation has been to translate the headers ([since 1.0.1](https://github.com/open-contracting/standard/blob/1__0__1/standard/schema/utils/translate_codelists.py#L23-L27)). Either CoVE needs to support translated headers, or we need to change our approach to translation.

**Comment by jpmckinney** [comment]
@duncandewhurst Should we merge this PR, and pursue a resolution in a new issue (whether in CoVe, or in `standard` if we change our translation approach)?

**Comment by duncandewhurst** [comment]
@jpmckinney I think so, as providing the translated extension may still be of use, even if CoVE can't currently patch it correctly.

**Review by duncandewhurst — APPROVED** [review]

**Comment by jpmckinney** [comment]
I created a follow-up issue here https://github.com/OpenDataServices/cove/issues/1042

**Comment by duncandewhurst** [comment]
great, thank you!

**Pull request merged**
