### PR TITLE
Update to latest versions of extensions, OCDS and OCDS Show

### PR DESCRIPTION
**Pull request by jpmckinney**
Also, closes #203

### CODE REVIEW

**Comment by jpmckinney** [comment]
It's failing because standard-maintenance-scripts is pointing to standard HEAD to be ready for OCDS 1.1.4, which leads to an inconsistency between PPP's currency.csv and the enum in the standard's release-schema.json.

This PR can wait until OCDS 1.1.4 is released, at which time we can update the base release schema and codelists.

**Comment by jpmckinney** [comment]
Realizing we need to copy over updated schema and codelist translations from the standard repo.

**Comment by jpmckinney** [comment]
Done copying translations, and updated handbook with new instructions.

**Comment by jpmckinney** [comment]
@duncandewhurst Please review. After merging, it'd be good to try to schedule some of the other issues, and then make a new release.

**Review by duncandewhurst — APPROVED** [review]

**Comment by duncandewhurst** [comment]
Closes #208

**Comment by jpmckinney** [comment]
Oops, meant to write 208 in issue description not 203 (this PR). Thanks!

**Pull request merged**
